### ISSUE TITLE
"ClanCapital" village missing in enum

### ISSUE THREAD

**Issue by dev-vinz** [tparviainen/clashofclans#153]
**Describe the bug**
It throws an error when trying to get informations about a player.

**To Reproduce**
Call any method to get player information, for example
`await client.Players.GetPlayerAsync(OWNER_TAG);`

**Expected behavior**
To parse correctly the village

**Execution Environment (please complete the following information):**
 - .NET version: .NET 6
 - ClashOfClans NuGet version: 8.8.0

**Proposal correction**
As far as I've seen, simply add `ClanCapital` into [Village](https://github.com/tparviainen/clashofclans/blob/develop/src/ClashOfClans.Models/Enums/Village.cs) enum

**Additional context**
![image](https://github.com/tparviainen/clashofclans/assets/48490315/40aee54c-64a0-47af-813e-f0fc973c62bc)

**Comment by tparviainen** [comment]
Thanks for reporting this issue! This will be fixed from version 8.8.1-rc1 (pre-release) onwards.

**Comment by tparviainen** [comment]
There is now also version [8.8.1](https://www.nuget.org/packages/ClashOfClans/8.8.1) of the NuGet package available which has this fix.
