### ISSUE TITLE
Could we have townHallLevel in clanMember class?

### ISSUE THREAD

**Issue by harrylai** [tparviainen/clashofclans#174]
COC API documentation states ClanMember type has `TownHallLevel: integer`, could we have it here as well? Thank you!

**Comment by tparviainen** [comment]
Thanks for reporting this issue! This is fixed in version [8.8.3](https://www.nuget.org/packages/ClashOfClans/8.8.3) of the ClashOfClans nuget package.

**Comment by harrylai** [comment]
Thank you so much!
