### ISSUE TITLE
Hey! Could we have latest update in nuget package?

### ISSUE THREAD

**Issue by harrylai** [tparviainen/clashofclans#180]
**Describe the bug**
It seems ClashOfClans -Version 8.8.3 does not have latest change included yet. Could we have that updated. Thank you!

**Comment by tparviainen** [comment]
Version [9.0.0-rc1](https://www.nuget.org/packages/ClashOfClans/9.0.0-rc1) contains the latest changes (obsolete APIs have been removed and there is a support for hero equipment), however there are few changes that I need to do before I release the official 9.0.0 release but hopefully the 9.0.0-rc1 pre-release is suitable as of now.

**Comment by tparviainen** [comment]
I will close this issue because latest release [9.0.0](https://www.nuget.org/packages/ClashOfClans) contains all changes including hero equipment.
